services:
  log-server:
    build:
      context: ./log_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  consensus-proposer-1:
    image: paxos_server
    build:
      context: ./paxos_server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PAXOS_ROLE=proposer
      - LOG_SERVER=http://log-server:8080/log
      - PAXOS_ACCEPTOR_NODES=http://consensus-proposer-1:8081,http://consensus-proposer-2:8082,http://consensus-acceptor-1:8083
      - PAXOS_LEARNER_NODES=http://consensus-proposer-1:8081,http://consensus-proposer-2:8082,http://consensus-acceptor-1:8083
      - NODE_ID=1
      - PORT=8081
  consensus-proposer-2:
    image: paxos_server
    ports:
      - "8082:8082"
    environment:
      - PAXOS_ROLE=proposer
      - LOG_SERVER=http://log-server:8080/log
      - PAXOS_ACCEPTOR_NODES=http://consensus-proposer-1:8081,http://consensus-proposer-1:8082,http://consensus-acceptor-1:8083
      - PAXOS_LEARNER_NODES=http://consensus-proposer-1:8081,http://consensus-proposer-2:8082,http://consensus-acceptor-1:8083
      - NODE_ID=2
      - PORT=8082
  consensus-acceptor-1:
    image: paxos_server
    ports:
      - "8083:8083"
    environment:
      - PAXOS_ROLE=acceptor
      - LOG_SERVER=http://log-server:8080/log
      - PAXOS_ACCEPTOR_NODES=http://consensus-proposer-1:8081,http://consensus-proposer-2:8082,http://consensus-acceptor-1:8083
      - PAXOS_LEARNER_NODES=http://consensus-proposer-1:8081,http://consensus-proposer-2:8082,http://consensus-acceptor-1:8083
      - NODE_ID=3
      - PORT=8083
