services:
  log-server:
    build:
      context: ./log_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  consensus-proposer-1:
    image: paxos_server
    build:
      context: ./paxos_server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PAXOS_ROLE=proposer
      - LOG_SERVER=http://log-server:8080/log
      - PAXOS_NODES=http://consensus-proposer-1:8080,http://consensus-proposer-2:8080,http://consensus-acceptor-1:8080
      - NODE_ID=1
  consensus-proposer-2:
    image: paxos_server
    ports:
      - "8082:8080"
    environment:
      - PAXOS_ROLE=proposer
      - LOG_SERVER=http://log-server:8080/log
      - PAXOS_NODES=http://consensus-proposer-1:8080,http://consensus-proposer-1:8080,http://consensus-acceptor-1:8080
      - NODE_ID=2
  consensus-acceptor-1:
    image: paxos_server
    ports:
      - "8083:8080"
    environment:
      - PAXOS_ROLE=acceptor
      - LOG_SERVER=http://log-server:8080/log
      - PAXOS_NODES=http://consensus-proposer-1:8080,http://consensus-proposer-2:8080,http://consensus-acceptor-1:8080
      - NODE_ID=3
