services:
  log-server:
    build:
      context: ./log_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  consensus-1:
    build:
      context: ./paxos_server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PAXOS_ROLES=proposer
      - LOG_SERVER=http://log-server:8080/log
    links:
      - log-server
